version: 2

sources:
  - name: public
    description: ""
    tables:
      - name: sensor_log
        description: ""
        columns:
          - name: power_timestamp
            description: ""
          - name: power_device_name
            description: ""
          - name: power_breaker_status
            description: ""
          - name: power_consumption
            description: ""
          - name: l1_phase_voltage
            description: ""
          - name: l2_phase_voltage
            description: ""
          - name: l3_phase_voltage
            description: ""
          - name: l1_phase_current
            description: ""
          - name: l2_phase_current
            description: ""
          - name: l3_phase_current
            description: ""
          - name: humidity
            description: ""
          - name: temperature
            description: ""