version: '3.7'

services:
  web:
    image: data-logger:v1
    ports:
      - "5000:5000"
    environment:
      PG_DB_PASSWORD: "${PG_DB_PASSWORD}"
      PG_DB_USERNAME : "${PG_DB_USERNAME}"
      PG_DB_NAME : "${PG_DB_NAME}"
      PG_DB_HOST : "${PG_DB_HOST}"
      PG_DB_PORT : "${PG_DB_PORT}"
    network_mode: host
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "${PG_DB_PASSWORD}"
      POSTGRES_USER : "${PG_DB_USERNAME}"
      POSTGRES_DB : "${PG_DB_NAME}"
    ports:
      - "${PG_DB_PORT}:5432"
    expose:
      - "5432"
    restart: always
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-exercise-db-volume:/var/lib/postgresql/data # persist the db
volumes:
  postgres-exercise-db-volume: